     # - curl -L --verbose https://accounts.google.com/.well-known/openid-configuration
     # - Bitbucket: Register a new OAuth consumer on https://bitbucket.org/account/user/<your username>/oauth-consumers/new and add the permission 'Account' - 'Read'
     # - Dropbox: Create a new application at https://www.dropbox.com/developers/apps
     # - Facebook: Register a new application at https://developers.facebook.com/apps and add the product "Facebook Login"
     # - GitHub: Register a new OAuth application on https://github.com/settings/applications/new
     # - GitLab: Register a new application on https://gitlab.com/profile/applications
     # - Google+: Obtain OAuth2 client credentials from the Google API console at https://console.developers.google.com/
     # - OpenID Connect: Use the OpenID Connect Discovery URL (<server>/.well-known/openid-configuration) to specify the endpoints
     # - Twitter: Go to https://dev.twitter.com/apps, create an application and ensure that the “Allow this application to be used to Sign in with Twitter” option is enabled
     # - Discord: Register a new application on https://discordapp.com/developers/applications/me
- provider_name: Google
  register_url: https://console.developers.google.com/
  logo_url: /auth/images/google/2x/btn_google_signin_light_normal_web@2x.png
  discovery_url: https://accounts.google.com/.well-known/openid-configuration
